/**
 * Seller lead intake (POST /api/leads, spec 4.2).
 *
 *   1. Validate (zod). Spam gets a silent ok; a repeated submissionId gets ok
 *      without a second delivery.
 *   2. Deliver to every durable sink in parallel (src/lib/sinks): Airtable,
 *      webhooks (e.g. the Google Sheets backup) and the owner alert email.
 *      One success is enough. If none is configured or all fail, the record
 *      is logged as [lead:undelivered] and the form shows the call-or-text
 *      fallback (502). Only in development does "nothing configured" pass.
 *   3. After the response: the owner text (Quo), the owner push (ntfy) and
 *      the seller's confirmation (src/lib/notify).
 */
import { z } from "zod";
import { site } from "@/config/site";
import { deployEnv, type DeployEnv } from "@/lib/env";
import {
  clientIp,
  fieldErrors,
  forgetSubmission,
  isDuplicateSubmission,
  isLikelySpam,
  json,
  rateLimit,
  readJson,
  type Env,
  type Fetch,
} from "@/lib/delivery";
import { CONDITIONS, OCCUPANCY, PROPERTY_TYPES, REASONS, TIMELINES, values, type Option } from "@/lib/lead-options";
import { phoneSchema } from "@/lib/schemas";
import { deliver } from "@/lib/sinks";
import { afterLead } from "@/lib/notify";
import { touchSchema } from "@/lib/touch";

export { isLikelySpam, resetRateLimit } from "@/lib/delivery";
export { phoneSchema } from "@/lib/schemas";

const optionalText = (max: number) => z.string().trim().max(max).optional().default("");
const optionalChoice = (choices: [string, ...string[]]) =>
  z.union([z.enum(choices), z.literal("")]).optional().default("");

export const leadSchema = z.object({
  address: z.string().trim().min(5, "Enter the street address and city").max(200),
  name: z.string().trim().min(2, "Enter your name").max(100),
  phone: phoneSchema,
  email: z.union([z.email("Enter an email like name@example.ca, or leave it blank").max(200), z.literal("")]).optional().default(""),
  propertyType: optionalChoice(values(PROPERTY_TYPES)),
  condition: optionalChoice(values(CONDITIONS)),
  timeline: optionalChoice(values(TIMELINES)),
  occupancy: optionalChoice(values(OCCUPANCY)),
  reason: optionalChoice([...REASONS]),
  notes: optionalText(2000),
  smsConsent: z.boolean().optional().default(false),
  /** Generated by the form on mount, so a double-tap or retry isn't delivered twice. */
  submissionId: z.string().trim().max(64).optional(),
  // Attribution (spec 8.2).
  page: optionalText(300),
  referrer: optionalText(500),
  utm: z.record(z.string(), z.string().max(200)).optional().default({}),
  firstTouch: touchSchema,
  lastTouch: touchSchema,
  // Spam signals.
  startedAt: z.number().optional(),
  website: optionalText(200),
});

export type LeadInput = z.output<typeof leadSchema>;

export type Lead = Omit<LeadInput, "website" | "startedAt"> & {
  id: string;
  receivedAt: string;
  userAgent: string;
};

export function toLead(input: LeadInput, userAgent: string, now = new Date()): Lead {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { website, startedAt, ...rest } = input;
  return { ...rest, id: crypto.randomUUID(), receivedAt: now.toISOString(), userAgent: userAgent.slice(0, 300) };
}

/** The visitor-facing label for a stored option value. */
export function optionLabel(options: readonly Option[], value: string): string {
  return options.find((o) => o.value === value)?.label ?? value;
}

export const UNDELIVERED_MESSAGE = `Your request didn't go through. Please call or text me at ${site.phone}.`;

type Deps = {
  env?: Env;
  fetchImpl?: Fetch;
  now?: number;
  /** Runs work after the response (next/server `after` in the route); defaults to fire-and-forget. */
  defer?: (task: () => Promise<void>) => void;
  /** Defaults to deployEnv(). */
  mode?: DeployEnv;
};

export async function handleLeadRequest(request: Request, deps: Deps = {}): Promise<Response> {
  const env = deps.env ?? process.env;
  const fetchImpl = deps.fetchImpl ?? fetch;
  const now = deps.now ?? Date.now();

  if (!rateLimit(`lead:${clientIp(request)}`, now)) {
    return json({ ok: false, error: `Too many requests. Please call or text me at ${site.phone}.` }, 429);
  }

  const read = await readJson(request);
  if ("error" in read) return read.error;

  const parsed = leadSchema.safeParse(read.body);
  if (!parsed.success) {
    return json({ ok: false, error: "Please fix the fields marked below.", fieldErrors: fieldErrors(parsed.error.issues) }, 400);
  }

  // Pretend spam succeeded so bots don't learn what tripped the filter.
  if (isLikelySpam(parsed.data, now)) return json({ ok: true });
  if (isDuplicateSubmission(parsed.data.submissionId, now)) return json({ ok: true, duplicate: true });

  const lead = toLead(parsed.data, request.headers.get("user-agent") ?? "", new Date(now));
  const result = await deliver("seller_lead", lead, { env, fetchImpl });

  if (result.delivered.length === 0) {
    if (result.configured === 0 && (deps.mode ?? deployEnv()) === "development") {
      console.warn("[lead] No lead destination is configured (fine in development). The lead:", JSON.stringify(lead));
    } else {
      console.error(`[lead:undelivered] ${JSON.stringify(lead)}`);
      forgetSubmission(parsed.data.submissionId);
      return json({ ok: false, undelivered: true, error: UNDELIVERED_MESSAGE }, 502);
    }
  }

  const defer = deps.defer ?? ((task) => void task());
  defer(async () => {
    await afterLead(lead, { env, fetchImpl, now: new Date(now) });
  });
  return json({ ok: true, id: lead.id });
}
